fs = require 'fs'
expect = require('chai').expect

fixtures = require './fixtures/data'
helpers = require './helpers'


describe 'VCF Import/Export', ->

    before helpers.startServer
    before helpers.clearDb
    before helpers.createContact fixtures.contact1

    before helpers.makeTestClient
    after  helpers.killServer


    describe 'Export a single contact', ->

        it 'GET /contacts/:contactid/:fn.vcf', (done) ->

            @client.get "/contacts/#{@contact.id}/james.vcf", done, false


        it 'should return the contact VCF export', (done) ->
            # UID is radomly generated by couch, we ca'nt test it.
            body = @body.replace /UID:[0-9a-f]*\n/g, ''
            expect(body).to.equal """
BEGIN:VCARD
VERSION:3.0
N:Smith;John;;;
FN:John Smith
NOTE:notes
TEL;TYPE=HOME:+331234567
TEL;TYPE=WORK:12584367
EMAIL;TYPE=HOME:jsmith@test.com
ADR;TYPE=HOME:;;14 Avenue de la République\\, 60200 Compiègne\\, Picardie\\, France;;;;
END:VCARD

"""
            done()
